Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
